### PR TITLE
Second milestone of the newsweek project

### PR DESCRIPTION
**Pull request by Shaher-11**
This is the second milestone of the Newsweek project and the section are completely responsive and great usage of bootstrap

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑🛑🛑**

Hello team,
Great work. Your designing skills are impressive. I salute you👏👏.
While this is an impressive project, some few changes are required to make it impeccable.

[REQUIRED]: An image is not showing. kindly fix that. Here is the issue below.
errorReview

[REQUIRED]: As this project emphasizes on using bootstrap, you have some css styles that can be transformed in bootstrap.
An example is the top-footer class in css.
Kindly use bootstrap classes.

[REQUIRED]: I noticed that you have a lot of !important in your css file. Kindly remove them.

[REQUIRED]: Also to make sure that your web page starts at the very top of the page and covers the entire width.

[REQUIRED]: The goal of this project is to clone the news week website. Use the colors that are used in the website. In the footer you used a gray color. You can use a google chrome extension called color picker that helps you pick the exact colors from a website.

[REQUIRED]: On the responsiveness part when resizing, there is an issue on the tablet view as there are two navbars. Kindly fix it.

[REQUIRED]: The hamburger icon on a small screen shouldn't have a white background. Check the original page for reference.

[REQUIRED]: Also add some padding in the navbar, to the side.

That's it
tenor (5)

Make the requested changes and ask for another review👌
You got this👍👍
Happy coding💻💻

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Shaher-11 and @Deepakdanger 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [x] Please implement the other suggestion too, which are suggested by previous TSE
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Shaher-11** [comment]
Done all the required changes

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Shaher-11 and @Deepakdanger :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
