### PR TITLE
The third milestone of the newsweek project

### PR DESCRIPTION
**Pull request by Shaher-11**
This is the third milestone of the Newsweek project and this milestone consists of 4 sections which are
  Magazine,   Editor's pick,  the main news, as well as the last section for the subscription.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] **IN THE MAGAZINE** section should have only one card per line on the mobile screen
- [x] the subscribe and newsletter section should look like the original website
- [x] update the live demo link in the README.md

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by Shaher-11** [comment]
Done the required changes

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [x] Good Pull request description. :+1:
- [x]  Great job implementing the requested changes. :muscle:
- [x] Good use of semantic HTML :+1: 

To Improve :factory_worker:

- [x] Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.
- [x] Images should conserve ratio like in the original web page


- [x] Please, align this title:


That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by Shaher-11** [comment]
Done the requested changes and made sure there is no commented code

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Shaher-11 and @Deepakdanger :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
