### PR TITLE
Fisrt milestone of the Newswek peoject

### PR DESCRIPTION
**Pull request by Shaher-11**
This is the first milestone of the Newsweek website and it consists of the header and the footer with intensive usage of bootstrap

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Shaher-11 and @Deepakdanger :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] The newsweek logo should be centred in desktop view and aligned to the left in tablet and mobile view.
* [x] The subscribe button should be a link and aligned to the right of the page on desktop view.
* [x] In mobile, the Login button changes into an icon


### Make the changes and request another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by Shaher-11** [comment]
Done the required changes

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
------------------
Hello @Shaher-11 @Deepakdanger  :wave: You are doing an amazing job on this milestone :muscle: :1st_place_medal: 
However, there minor changes to make to full fit this milestone :hammer_and_wrench: see them below :eyes: :point_down: 
-------------

- [x] Your subscribe button must have a link `a` tag. Please change it. Just change for  `a` tag and put the classes of a button. E.g `<a type="button" class="btn btn-warning btn-lg font-weight-bold rounded-pill btn-lg">Subscribe ></a>`
- [x] Your subscribe button is still on the left of the page on the desktop. It must be on the right side. 
- [x] All your social media icon must have a links. E.g `<a href="#"><i class="fab fa-facebook-f text-dark"></i></a>`
-----------------
Make this required changes :hammer_and_wrench: and send it for another review :muscle: :100: 
HAPPY CODING!!

**Comment by Deepakdanger** [comment]
we have changes the code according to the review.
1)Added link to subscribe.
2)Added link to every icon.
3)Subscribe button on the right side of the desktop screen.

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @Shaher-11 and @Deepakdanger , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
